# Generated by Django 5.1.5 on 2025-02-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='component',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_new_component',
        ),
        migrations.AddField(
            model_name='service',
            name='components',
            field=models.ManyToManyField(to='serviceApi.component'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_new_components',
            field=models.JSONField(default=dict),
        ),
    ]
